#!/bin/bash

# This creates a free key entry that expires in 18 hours

# This can take a user ID argument to apply to existing users

date_reg_expires="$(date +%F\ %T -d "+18 hours")"
reg_key="$(pwgen -1 255)"
purchase_key="$(pwgen -1 255)"

if [ ! -z "$1" ]; then

  case $1 in
    ''|*[!0-9]*) exit 2 ;;
    *) user_id="$1" ;;
  esac

  if [ ! -z "$2" ] && [ "$2" = "update" ]; then
  # Make the database entry
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
UPDATE badaddb.freekeys SET purchase_key='$purchase_key', purchase_useable='live' WHERE user_id='$user_id';"

# Finish
echo "
Purchase: https://badad.one/new_ad.php?p=$purchase_key
"

  else

  # Make the database entry
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
INSERT INTO badaddb.freekeys (user_id, purchase_key) VALUES ('$user_id', '$purchase_key');"

# Finish
echo "
Purchase: https://badad.one/new_ad.php?p=$purchase_key
"

  fi

else

# Make the database entry
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
INSERT INTO badaddb.freekeys (reg_key, purchase_key, date_reg_expires) VALUES ('$reg_key', '$purchase_key', '$date_reg_expires');"

# Finish
echo "Links:
Register: https://badad.one/register.php?p=$reg_key
Purchase: https://badad.one/new_ad.php?p=$purchase_key
"

fi

