CREATE TABLE IF NOT EXISTS orders (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  ad_id BIGINT REFERENCES ads(id),
  email TEXT,
  total_cents INT NOT NULL,
  weeks INT NOT NULL DEFAULT 1,
  pay_via TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  provider_ref TEXT,
  renew BOOLEAN NOT NULL DEFAULT FALSE,
  period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crypto_payments (
  id BIGSERIAL PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE ads ADD COLUMN IF NOT EXISTS renew BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS pay_via TEXT;
