upstream badad_app { server 127.0.0.1:9003; }
server {
    listen 80;
    server_name badad.one;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://badad_app;
    }
}
